---
exchange:
  name: bybit
  api_key: some_key
  api_secret: some_secret

market:
  type: spot
  symbol: FTM/USDT

trade_algorithm: long

entry_condition:
  filters:
    - type: BB
      time_frame: 5m

exit_condition:
  mode: signal
  signal:
    filters:
      - name: BB
        time_frame: 15m
      - name: RSI
        time_frame: 15m
        condition:
          gt: 70
    pnl: 2
