---
exchange:
  id: bybit
  api_key: some_key
  api_secret: some_secret
  trading_mode: demo

market:
  type: spot
  symbol: BTC/USDT

trade_algorithm: long

entry_condition:
  filters:
    - type: BB
      time_frame: 5m
      periods: 20
      moving_average: sma

exit_condition:
  mode: signal
  signal:
    filters:
      - type: BB
        time_frame: 15m
      - type: RSI
        time_frame: 15m
        condition:
          operator: gt
          value: 70
    pnl: 2