---
exchange:
  id: bybit
  api_key: some_key
  api_secret: some_secret
  trading_mode: demo

market:
  type: spot
  symbol: BTC/USDT

deal:
  trade_algorithm: long

  entry_condition:
    filters:
      - indicator: BB
        timeframe: 5m
        condition:
          operator: lt
          name: "lower_value"

  exit_condition:
    mode: signal
    signal:
      filters:
        - indicator: BB
          timeframe: 15m
          condition:
            operator: gt
            name: "upper_value"
      pnl: 2
