#---
#root:
#    level: 'DEBUG'
#    handlers: [console_handler, file_handler]
#
#handlers:
#  console_handler:
#    level: 'DEBUG'
#
#  file_handler:
#    level: 'DEBUG'
#    filename: "/tmp/greedypet.log"
